// Generated by nitro
import type { Serialize, Simplify } from 'nitropack'
declare module 'nitropack' {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/auth/login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/login.post').default>>>>
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/login').default>>>>
    }
    '/api/auth/logout': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/logout').default>>>>
    }
    '/api/auth/register': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/register.post').default>>>>
    }
    '/api/auth/verify': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/verify.post').default>>>>
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/verify').default>>>>
    }
    '/api/modules': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/modules/index').default>>>>
    }
    '/api/user/progress': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/progress').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/renderer').default>>>>
    }
  }
}
export {}