// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 16/03/2025, 22:58:39
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/home/TheObserverHub/Bolt_Nuxt_Cilari_compliance/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/TheObserverHub/Bolt_Nuxt_Cilari_compliance/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/TheObserverHub/Bolt_Nuxt_Cilari_compliance/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/TheObserverHub/Bolt_Nuxt_Cilari_compliance/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/TheObserverHub/Bolt_Nuxt_Cilari_compliance/plugins/**/*.{js,ts,mjs}","/home/TheObserverHub/Bolt_Nuxt_Cilari_compliance/composables/**/*.{js,ts,mjs}","/home/TheObserverHub/Bolt_Nuxt_Cilari_compliance/utils/**/*.{js,ts,mjs}","/home/TheObserverHub/Bolt_Nuxt_Cilari_compliance/pages/admin/index.vue","/home/TheObserverHub/Bolt_Nuxt_Cilari_compliance/pages/admin/users/[id].vue","/home/TheObserverHub/Bolt_Nuxt_Cilari_compliance/pages/auth/login.vue","/home/TheObserverHub/Bolt_Nuxt_Cilari_compliance/pages/auth/register.vue","/home/TheObserverHub/Bolt_Nuxt_Cilari_compliance/pages/dashboard.vue","/home/TheObserverHub/Bolt_Nuxt_Cilari_compliance/pages/index.vue","/home/TheObserverHub/Bolt_Nuxt_Cilari_compliance/pages/modules/[id].vue","/home/TheObserverHub/Bolt_Nuxt_Cilari_compliance/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/TheObserverHub/Bolt_Nuxt_Cilari_compliance/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/TheObserverHub/Bolt_Nuxt_Cilari_compliance/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;